FROM alpine:3.15 as php-base
RUN apk update
RUN apk add --upgrade apk-tools
RUN apk upgrade --available
RUN apk add --no-cache \
    php7-mysqli \
    php7-bcmath \
    php7-zip \
    php7-fpm \
    php7-fileinfo \
    php7-pecl-redis \
    php7-opcache \
    php7-pdo_sqlite \
    php7-session \
    php7-sodium \
    php7-pecl-imagick \ 
    php7-cli \
    php7-tokenizer \
    php7-intl \ 
    php7-dom \ 
    php7-xml \
    php7-sockets \  
    php7-simplexml \ 
    php7-xmlwriter \
    php7-json \
    php7-openssl \
    php7-phar \
    php7-curl \
    php7-pdo_mysql \
    php7-posix \ 
    php7-pcntl \
    php7-pecl-apcu
#Now for what we shouldn't need in production  
# Required, because with i.e. php:7.4-fpm image it would require to compile exctensions, which requires gcc, g++ etc. This would make image even larger.
RUN apk add --no-cache \
    apache-ant \
    git \
    composer \
    bash \
    shadow \
    unzip \
    jq \
    curl \
    make
RUN rm -rf /var/cache/apk/* 