# Use ECR nginx, to ensure we comply with ECR-stuff.
FROM public.ecr.aws/nginx/nginx:latest

# Healthchecks are important, for us and our ALBS.
COPY nginx-parametrized/release-version-nginx.txt /usr/share/nginx/html/release-version-nginx.txt
#COPY nginx-parametrized/default.conf /etc/nginx/conf.d/default.conf
COPY nginx-parametrized/healthcheck.sh /healthcheck.sh
#COPY nginx-parametrized/template-variables.txt /etc/nginx/templates/10-variables.conf.template
COPY nginx-parametrized/run.sh .

RUN echo "OK" > /usr/share/nginx/html/healthcheck
CMD ["/bin/bash", "-c", "nginx;./run.sh"]