# Use ECR nginx, to ensure we comply with ECR-stuff.
FROM public.ecr.aws/nginx/nginx:latest

# Healthchecks are important, for us and our ALBS.
COPY nginx-source/healthcheck-install.txt /usr/share/nginx/html/healthcheck-install.txt
